#!/bin/groovy

@Library('plib')
import com.stack1.testlib.*

def packager = 'pipeline/package/package.groovy'

Handlers handlers = new Handlers( packager )

invoke( handlers )















//def z = new com.stack1.testlib.Zot()
//z.checkOutFrom("hw.git")
